import { AudioEngine } from './AudioEngine';
import { Asset } from '@jiggy/assets';
export declare class HTML5AudioEngine extends AudioEngine {
    private _backgroundAudios;
    private _soundEffects;
    private _backgroundVolume;
    private _soundEffectVolume;
    constructor();
    addBackgroundMusic(name: string, audio: Asset): void;
    addSoundEffect(name: string, audio: Asset): void;
    setBackgroundVolume(volume: number): void;
    setSoundEffectVolume(volume: number): void;
    isBackgroundMusic(audio: Asset): boolean;
    isSoundEffect(audio: Asset): boolean;
    protected _playAudio(audio: Asset): void;
    private _updateVolume(audio);
    protected _pauseAudio(audio: Asset): void;
    protected _stopAudio(audio: Asset): void;
    protected _isAudioLooping(audio: Asset): boolean;
    protected _loopAudio(audio: Asset, state: boolean): void;
    protected _isAudioMuted(audio: Asset): boolean;
    protected _muteAudio(audio: Asset, state: boolean): void;
    protected _getAudioDuration(audio: Asset): number;
    protected _setTimeCursor(audio: Asset, seconds: number): void;
    protected _getTimeCursor(audio: Asset): number;
    protected _setVolume(audio: Asset, volume: number): void;
    protected _getVolume(audio: Asset): number;
    protected _registerStartEvent(audio: Asset): void;
    protected _registerEndEvent(audio: Asset): void;
}
